import type { Occurrence, User } from "./types"

export const mockUser: User = {
  id: "user-1",
  name: "Maria Silva",
  email: "maria.silva@email.com",
  isAdmin: false,
  avatar: undefined,
}

export const mockAdminUser: User = {
  id: "admin-1",
  name: "Carlos Admin",
  email: "admin@fiscaliza.sp.gov.br",
  isAdmin: true,
  avatar: undefined,
}

export const initialOccurrences: Occurrence[] = [
  {
    id: "occ-1",
    title: "Buraco perigoso na Avenida Paulista",
    description:
      "Grande buraco na pista da direita, próximo ao número 1500. O buraco tem aproximadamente 50cm de diâmetro e 20cm de profundidade. Já causou danos a diversos veículos e representa risco para motociclistas e ciclistas.",
    category: "buraco",
    status: "em_analise",
    initialPriority: "alta",
    priorityVotes: { baixa: 2, media: 8, alta: 45 },
    neighborhood: "Bela Vista",
    address: "Avenida Paulista, 1500",
    createdAt: new Date("2026-01-15T10:30:00"),
    supports: 127,
    confirmations: 89,
    contestations: 3,
    existenceContestations: 0,
    latitude: -23.5629,
    longitude: -46.6544,
    comments: [
      {
        id: "c1",
        author: "João Pedro",
        message: "Passei por aqui ontem e quase danifiquei meu carro. Urgente!",
        createdAt: new Date("2026-01-16T08:00:00"),
      },
      {
        id: "c2",
        author: "Ana Costa",
        message: "Já faz duas semanas que está assim. Precisamos de ação rápida.",
        createdAt: new Date("2026-01-17T14:30:00"),
      },
    ],
    imageUrl: "/placeholder-buraco.jpg",
  },
  {
    id: "occ-2",
    title: "Poste sem iluminação na Consolação",
    description:
      "Poste apagado há mais de uma semana na Rua da Consolação, próximo à estação de metrô. A área fica muito escura à noite, causando insegurança para pedestres e comerciantes locais.",
    category: "iluminacao",
    status: "pendente",
    initialPriority: "media",
    priorityVotes: { baixa: 5, media: 22, alta: 18 },
    neighborhood: "Consolação",
    address: "Rua da Consolação, 2100",
    createdAt: new Date("2026-01-18T16:45:00"),
    supports: 56,
    confirmations: 34,
    contestations: 1,
    existenceContestations: 0,
    latitude: -23.5505,
    longitude: -46.6595,
    comments: [
      {
        id: "c3",
        author: "Roberto Lima",
        message: "Trabalho aqui perto e é muito perigoso sair tarde.",
        createdAt: new Date("2026-01-19T18:00:00"),
      },
    ],
    imageUrl: "/placeholder-iluminacao.jpg",
  },
  {
    id: "occ-3",
    title: "Vazamento de água na Vila Mariana",
    description:
      "Vazamento constante de água na calçada da Rua Domingos de Morais. A água está escorrendo há pelo menos 3 dias, desperdiçando recursos hídricos e criando poças que atrapalham pedestres.",
    category: "vazamento",
    status: "pendente",
    initialPriority: "alta",
    priorityVotes: { baixa: 1, media: 6, alta: 28 },
    neighborhood: "Vila Mariana",
    address: "Rua Domingos de Morais, 800",
    createdAt: new Date("2026-01-20T09:15:00"),
    supports: 42,
    confirmations: 28,
    contestations: 0,
    existenceContestations: 0,
    latitude: -23.5892,
    longitude: -46.6389,
    comments: [
      {
        id: "c4",
        author: "Fernanda Souza",
        message: "O desperdício de água é absurdo, principalmente em época de crise hídrica.",
        createdAt: new Date("2026-01-21T11:20:00"),
      },
      {
        id: "c5",
        author: "Marcos Oliveira",
        message: "Já liguei para a Sabesp mas não vieram ainda.",
        createdAt: new Date("2026-01-21T15:45:00"),
      },
    ],
    imageUrl: "/placeholder-vazamento.jpg",
  },
  {
    id: "occ-4",
    title: "Acúmulo de lixo irregular na Praça da Sé",
    description:
      "Grande quantidade de lixo acumulado próximo às bancas de jornal na Praça da Sé. Há restos de comida, garrafas e outros detritos que estão atraindo pragas urbanas e causando mau cheiro.",
    category: "lixo",
    status: "resolvida",
    initialPriority: "media",
    priorityVotes: { baixa: 8, media: 15, alta: 12 },
    neighborhood: "Sé",
    address: "Praça da Sé, s/n",
    createdAt: new Date("2026-01-10T07:30:00"),
    supports: 89,
    confirmations: 67,
    contestations: 12,
    existenceContestations: 0,
    latitude: -23.5505,
    longitude: -46.6333,
    comments: [
      {
        id: "c6",
        author: "Patricia Mendes",
        message: "Finalmente limparam! Obrigada a todos que apoiaram.",
        createdAt: new Date("2026-01-14T09:00:00"),
      },
      {
        id: "c7",
        author: "Lucas Santos",
        message: "Limparam parcialmente, ainda tem lixo em alguns pontos.",
        createdAt: new Date("2026-01-14T16:30:00"),
      },
    ],
    imageUrl: "/placeholder-lixo.jpg",
  },
  {
    id: "occ-5",
    title: "Placa de PARE danificada em Pinheiros",
    description:
      "Placa de sinalização de PARE completamente torta e ilegível na esquina da Rua dos Pinheiros com a Rua Teodoro Sampaio. Risco de acidentes no cruzamento movimentado.",
    category: "sinalizacao",
    status: "em_analise",
    initialPriority: "alta",
    priorityVotes: { baixa: 3, media: 11, alta: 31 },
    neighborhood: "Pinheiros",
    address: "Rua dos Pinheiros, 900",
    createdAt: new Date("2026-01-19T13:00:00"),
    supports: 73,
    confirmations: 51,
    contestations: 2,
    existenceContestations: 2,
    latitude: -23.5667,
    longitude: -46.6811,
    comments: [
      {
        id: "c8",
        author: "Carla Ribeiro",
        message: "Quase aconteceu um acidente aqui ontem por causa disso.",
        createdAt: new Date("2026-01-20T08:15:00"),
      },
      {
        id: "c9",
        author: "Diego Almeida",
        message: "Já reportei na CET também, espero que resolvam logo.",
        createdAt: new Date("2026-01-20T17:40:00"),
      },
      {
        id: "c10",
        author: "Juliana Martins",
        message: "Moro perto e vejo carros quase batendo toda hora.",
        createdAt: new Date("2026-01-21T10:00:00"),
      },
    ],
    imageUrl: "/placeholder-sinalizacao.jpg",
  },
]
